name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: x64

      - name: Install dependencies
        run: |
          npm install
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip wheel setuptools
          pip install aiohttp

      - name: Build
        run: |
          npm run build

      - name: Publish
        env:
          SERVER: ${{ secrets.SERVER }}
          KEY: ${{ secrets.KEY }}
        run: |
          source venv/bin/activate
          python .github/build/upload.py